version: '3.8'
services:

  #---------------
  # Mosquito MQTT
  #---------------

  mosquitto:
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto:2.0
    command: "mosquitto -c /mosquitto-no-auth.conf"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto

  #-------------
  # Zigbee2MQTT
  #-------------

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    ports:
      - "8080:8080"
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Madrid
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0

  #---------
  # Grafana
  #---------

  grafana:
    hostname: grafana
    container_name: grafana
    restart: unless-stopped
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
